id: I5F6CF79D
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:25:44.366943
last_modified: 2023-02-08 15:25:44.367116
source_metadata:
  title: Tathāgatagarbhasūtra
  language: bo
bases:
  293B:
    base_file: 293B.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
